import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

test('research library is authenticated, versioned, and source-backed', async () => {
  const source = await readFile(new URL('../app/markets/research/page.tsx', import.meta.url), 'utf8')
  const route = await readFile(new URL('../app/api/markets/research/route.ts', import.meta.url), 'utf8')
  const report = await readFile(new URL('../app/markets/stocks/[symbol]/research/page.tsx', import.meta.url), 'utf8')
  const action = await readFile(new URL('../components/markets/ResearchActionButton.tsx', import.meta.url), 'utf8')
  const queue = await readFile(new URL('../components/markets/ResearchQueue.tsx', import.meta.url), 'utf8')
  const progress = await readFile(new URL('../components/markets/ResearchProgressRing.tsx', import.meta.url), 'utf8')
  const dateFormatting = await readFile(new URL('../lib/markets/format-date.ts', import.meta.url), 'utf8')
  const worker = await readFile(new URL('../lib/server/company-research.ts', import.meta.url), 'utf8')
  assert.match(source, /requireAllowedMarketUser/)
  assert.match(source, /fetchEquityResearchLibrary/)
  assert.match(source, /fetchResearchJobs/)
  assert.match(source, /<ResearchQueue/)
  assert.match(source, /Immutable research versions/)
  assert.match(source, /fetchFinanceReports/)
  assert.match(route, /\^\[A-Z\]\[A-Z0-9.-\]/)
  assert.match(route, /generate-company-research/)
  assert.match(route, /export async function GET/)
  assert.match(route, /Cache-Control': 'private, no-store/)
  assert.match(action, /setInterval\(\(\) => void poll\(\), 2_500\)/)
  assert.match(action, /router\.refresh\(\)/)
  assert.match(queue, /View research queue|ResearchProgressRing/)
  assert.match(progress, /strokeDashoffset: 100 - progress/)
  assert.match(source, /formatMarketDate\(note\.generatedAt\)/)
  assert.match(queue, /formatMarketDateTime\(job\.updatedAt\)/)
  assert.match(dateFormatting, /America\/New_York/)
  assert.match(worker, /Synthesizing 15-section analysis/)
  assert.match(worker, /Validating and publishing research/)
  assert.match(report, /REPORT_CHAPTERS\.map/)
  assert.match(report, /Business & competitive engine/)
  assert.match(report, /Where the revenue comes from/)
  assert.match(report, /comparableTaxonomy/)
  assert.match(report, /Reported geography \/ segment mix/)
  assert.match(report, /Revenue composition is not profit composition/)
  assert.match(report, /The numbers behind the thesis/)
  assert.match(report, /<InteractivePriceChart/)
  assert.match(report, /<ResearchFinancialChart/)
  assert.match(report, /Cash \+ short investments/)
  assert.match(report, /Reconciled position/)
  assert.match(report, /FCF yield \(provider\)/)
  assert.match(report, /Forward estimates/)
  assert.match(report, /Sources used in version/)
})
