import test from 'node:test'
import assert from 'node:assert/strict'
import { currentAdvice } from './fixtures/research-advice-v2.ts'
import { validateResearchAdvice } from '../lib/markets/research-advice.ts'
import { hasCurrentResearchContract,validatePacketDecisionSupport,type EvidenceGap } from '../lib/markets/research-contract.ts'
import { gateRecommendation,abstention,type DecisionContext,type DecisionName } from '../lib/markets/recommendations.ts'
import { classifyResearchRefresh } from '../lib/markets/research-refresh.ts'
import { recommendationResearchTargets } from '../lib/markets/recommendation-preparation.ts'
const gap:EvidenceGap={id:'cash-flow',question:'Cash flow detail is absent from the captured evidence.',kind:'missing_fact',dataKeys:['cash flow'],blockingActions:['buy','add'],sourceIds:['s'],followUp:{trigger:'The next audited cash flow statement.',nextCheckAt:null}}
function fixture(){
 const advice=currentAdvice([gap]);advice.newEntryStance.value='wait';advice.evidenceSufficiency.value='insufficient'
 const name:DecisionName={symbol:'ABC',securityId:'security',portfolioId:'p',owned:true,quantity:1,currentWeightPct:5,portfolioValue:10000,cash:1000,quote:{price:100,asOf:'2026-10-02T20:00:00Z',feed:'iex'},research:{id:'r',content:{formalRating:'NOT_RATED',advice}},thesis:{status:'accepted'},sector:'Technology',averageDollarVolume:1000000,sources:['s'],gaps:['Missing company evidence: cash flow'],causalLinks:[],selectionReason:'owned'}
 const context:DecisionContext={id:'m',ownerId:'owner',date:'2026-10-03',cutoff:'2026-10-03T07:00:00Z',policy:'prospective-v1.7',codeVersion:'test',portfolio:[],names:[name],evidence:[{id:'s',kind:'primary',value:{},url:'https://example.com',asOf:'2026-10-02',availableAt:'2026-10-02',retrievedAt:'2026-10-02',feed:null,hash:'h'}],world:[],market:null,gaps:[],universe:[]}
 return {name,context,rec:{...abstention(name,context,'Supported ownership decision'),action:'hold' as const,sourceIds:['s'],gateReasons:[],entry:{trigger:'manual_condition' as const,condition:'Retain supported current exposure',maxPrice:null,targetWeightPct:5}}}
}
test('missing cash flow can block new risk without erasing cited ownership support',()=>{const {name,context,rec}=fixture();assert.doesNotThrow(()=>validateResearchAdvice((name.research!.content as {advice:unknown}).advice,['s']));assert.equal(gateRecommendation(rec,context).action,'hold');const result=gateRecommendation({...rec,action:'add'},context);assert.equal(result.action,'no_trade');assert.ok(result.gateReasons.includes('Missing company evidence: cash flow'));const advice=currentAdvice([gap]);advice.existingPositionStance.value='exit';advice.newEntryStance.value='wait';const sell=gateRecommendation({...rec,action:'sell',entry:{...rec.entry,targetWeightPct:0}},{...context,names:[{...name,research:{id:'r',content:{formalRating:'NOT_RATED',advice}}}]});assert.equal(sell.action,'sell')})
test('unknown limitations and stale identity/price still block supported actions',()=>{const {name,context,rec}=fixture();for(const patch of [{gaps:['Missing company evidence: new essential data']},{quote:null},{gaps:['Stable security identity is unavailable']}])assert.equal(gateRecommendation(rec,{...context,names:[{...name,...patch}]}).action,'no_trade')})
test('future uncertainty is scenario-supported, but missing essential evidence cannot be waived',()=>{const future={...gap,id:'adoption',kind:'future_uncertainty' as const,dataKeys:[],blockingActions:[]};assert.ok(hasCurrentResearchContract({advice:currentAdvice([future])}));const essential=currentAdvice([gap]);essential.newEntryStance.value='wait';essential.decisionSupport!.actionSupport.buy.status='supported';assert.throws(()=>validateResearchAdvice(essential,['s']),/essential blocker/);const omitted=currentAdvice();assert.throws(()=>validatePacketDecisionSupport(omitted,['cash flow']),/omitted input/);assert.throws(()=>validatePacketDecisionSupport(omitted,[],[{id:'product',unresolvedQuestions:['Adoption unknown'],sourceIds:['s']}]),/topic:product/)})
test('fresh legacy holdings are selected for upgrades, while full regeneration overrides unchanged marks',()=>{const {name,context}=fixture();assert.equal(recommendationResearchTargets({...context,names:[{...name,gaps:[],research:{id:'old',content:{formalRating:'HOLD'}}},{...name,portfolioId:'other',gaps:[]}]}).length,1);assert.equal(classifyResearchRefresh({priorPacket:{symbol:'ABC'},packet:{symbol:'ABC'},instrument:'equity',forceFullResearch:true}).kind,'full_research')})
